global:
  scrape_interval: 5s # 每 5 秒抓一次数据 (Demo 设快点方便看效果)

scrape_configs:
  - job_name: 'ml_model_monitor'
    static_configs:
      # 'ml_app' 是 docker-compose 中定义的服务名
      # 5000 是 app.py 监听的端口
      - targets: ['ml_app:5000']